
$(function () {
    var countryData = {
        "Austria": {
            "description":"<h1>Austria</h1><ul> <li><strong>History: </strong>Austria has a rich history, once the center of the powerful Habsburg monarchy. It played a significant role in European politics, especially during the Renaissance and Baroque periods;</li> <li><strong>Economy: </strong> Austria has a highly developed market economy with a strong focus on services, industry, and tourism;</li> <li><strong>Culture & Traditions: </strong> Austria is known for its classical music, with famous composers like Mozart and Strauss. It also has a vibrant arts scene, particularly in Vienna;</li> <li><strong>Languages: </strong> German is the official language;</li> <li><strong>When to Visit: </strong> The best time to visit Austria is during the summer months (June to August) when the weather is warm and ideal for outdoor activities;</li> <li><strong>Hints: </strong> Don't miss exploring the stunning architecture of Vienna, Salzburg's charming old town, and the picturesque landscapes of the Austrian Alps.</li></ul>",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Flag_of_Austria.svg/300px-Flag_of_Austria.svg.png"
        },
        
        "Belgium": {
            "description":"<h1>Belgium</h1> <ul> <li><strong>History: </strong>Belgium has a complex history due to its strategic location and linguistic diversity. It was once part of various European empires and later became independent in 1830;</li> <li><strong>Economy: </strong>  Belgium has a highly developed and diversified economy, with a strong focus on international trade, manufacturing, and services;</li> <li><strong>Culture & Traditions: </strong> Belgium is famous for its chocolates, waffles, and beer. It also has a rich cultural heritage, with medieval towns, Renaissance architecture, and world-class museums;</li> <li><strong>Languages: </strong> Dutch, French, and German are the official languages;</li> <li><strong>When to Visit:</strong> Belgium can be visited year-round, but the summer months (June to August) are particularly pleasant for exploring its cities and countryside;</li> <li><strong>Hints: </strong>Spend time exploring Brussels' Grand Place, tasting Belgian chocolates in Bruges, and visiting historic sites like the Battle of Waterloo.</li></ul>",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Belgium.svg/300px-Flag_of_Belgium.svg.png"
        },
        "Cyprus": {
            "description":"<h1>Cyprus</h1> <ul> <li><strong>History: </strong> Cyprus has a long and diverse history, with influences from ancient civilizations such as the Greeks, Romans, Byzantines, and Ottomans. It became an independent republic in 1960;</li> <li><strong>Economy :</strong>  Cyprus has a mixed economy with a strong focus on services, tourism, and shipping;</li> <li><strong>Culture & Traditions: </strong> Cyprus has a rich cultural heritage, with traditional music, dance, and cuisine influenced by its diverse history. The island is also known for its stunning beaches and archaeological sites;</li> <li><strong>Languages: </strong>Greek and Turkish are the official languages;</li> <li><strong>When to Visit: </strong>The best time to visit Cyprus is during the spring (March to May) and autumn (September to November) when the weather is mild and ideal for outdoor activities; <li> <strong>Hints: </strong>Explore the ancient ruins of Kourion, relax on the beaches of Ayia Napa, and taste traditional Cypriot meze dishes.</li></ul>",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Flag_of_Cyprus.svg/300px-Flag_of_Cyprus.svg.png"
        },
        "Estonia": {
            "description":"<h1>Estonia</h1> <ul> <li><strong>History: </strong>Estonia has a history of being ruled by various powers, including the Danes, Swedes, and Russians. It gained independence in 1918 but was occupied by the Soviet Union during World War II;</li> <li><strong>Economy: </strong>  Estonia has a modern market economy with a strong focus on technology, innovation, and services;</li> <li><strong>Culture & Traditions: </strong>  Estonia has a unique cultural heritage, with influences from its Nordic, German, and Russian neighbors. It is known for its traditional music, dance, and handicrafts; </li> <li><strong>Languages: </strong>  Estonian is the official language;</li> <li><strong>When to Visit: </strong>The best time to visit Estonia is during the summer months (June to August) when the weather is warm and the days are long;</li> <li><strong>Hints: </strong> Explore the medieval old town of Tallinn, visit Lahemaa National Park for outdoor adventures, and experience the traditional sauna culture.</li></ul>",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Flag_of_Estonia.svg/300px-Flag_of_Estonia.svg.png"
        },
        "Finland": {
            "description":"<h1>Finland</h1> <ul> <li><strong>History: </strong> Finland has a history of being ruled by Sweden and Russia before gaining independence in 1917. It played a significant role in World War II and the Cold War;</li> <li><strong>Economy: </strong>  Finland has a highly industrialized and technologically advanced economy, with a strong focus on manufacturing, technology, and services;</li> <li><strong>Culture & Traditions: </strong>  Finland is known for its sauna culture, Midnight Sun, and Northern Lights. It has a rich tradition of music, literature, and design; </li> <li><strong>Languages:</strong>  Finnish and Swedish are the official languages;</li> <li><strong>When to Visit: </strong>The best time to visit Finland depends on your interests. Summer (June to August) is ideal for outdoor activities and enjoying the Midnight Sun, while winter (December to February) is perfect for experiencing the Northern Lights and winter sports;</li> <li><strong>Hints: </strong> Explore the capital city of Helsinki, visit the Finnish Lakeland region for outdoor adventures, and experience traditional Finnish cuisine like reindeer dishes and Karelian pastries.</li></ul>",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Finland.svg/300px-Flag_of_Finland.svg.png"
        },
        "France": {
            "description":"<h1>France</h1> <ul> <li><strong>History: </strong> France has a long and complex history, from the Roman Empire to the French Revolution and beyond. It has been a major player in European politics, culture, and art;</li> <li><strong>Economy: </strong>France has one of the largest and most diversified economies in the world, with a strong focus on manufacturing, tourism, and services;</li> <li><strong>Culture & Traditions: </strong> France is known for its art, cuisine, fashion, and literature. It has a rich cultural heritage, with iconic landmarks like the Eiffel Tower, Louvre Museum, and Notre-Dame Cathedral; </li> <li><strong>Languages: </strong>  French is the official language;</li> <li><strong>When to Visit: </strong>The best time to visit France depends on your interests. Spring (March to May) and autumn (September to November) are generally considered the best times to avoid crowds and enjoy mild weather;</li> <li><strong>Hints:</strong> Explore the romantic city of Paris, taste French wine in the vineyards of Bordeaux, and relax on the beaches of the French Riviera.</li></ul>",
            "image": "https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/300px-Flag_of_France.svg.png"
        },
        "Germany": {
            "description":"<h1>Germany</h1> <ul> <li><strong>History: </strong> Germany has a long and complex history, from the Holy Roman Empire to the two World Wars and reunification in 1990. It has been a major cultural and economic force in Europe;</li> <li><strong>Economy: </strong>   Germany has the largest economy in Europe and the fourth-largest in the world. It is known for its strong manufacturing sector, particularly in automotive and engineering industries;</li> <li><strong>Culture & Traditions: </strong>   Germany is known for its beer, sausages, and festivals like Oktoberfest. It has a rich cultural heritage, with famous composers like Beethoven and Bach, as well as iconic landmarks like the Brandenburg Gate and Neuschwanstein Castle; </li> <li><strong>Languages: </strong> German is the official language;</li> <li><strong>When to Visit: </strong>The best time to visit Germany depends on your interests. Spring (April to June) and autumn (September to October) are generally pleasant for sightseeing, while December is perfect for experiencing traditional Christmas markets;</li> <li><strong>Hints:</strong>  Explore the historic city of Berlin, visit the fairy-tale towns of the Romantic Road, and hike in the scenic Black Forest.</li></ul>",
            "image": "https://upload.wikimedia.org/wikipedia/en/thumb/b/ba/Flag_of_Germany.svg/300px-Flag_of_Germany.svg.png"
        },
        "Greece": {
            "description":"<h1>Greece</h1> <ul> <li><strong>History strong> Greece is considered the cradle of Western civilization, with a history dating back to ancient times. It was the birthplace of democracy, philosophy, and the Olympic Games;</li> <li><strong>Economy: </strong> Greece has a mixed economy with a strong focus on tourism, shipping, and agriculture. It has faced economic challenges in recent years but remains a popular tourist destination;</li> <li><strong>Culture & Traditions: </strong>   Greece is known for its ancient ruins, beautiful islands, and vibrant culture. It has a rich tradition of music, dance, and cuisine; </li> <li><strong>Languages: </strong> Greek is the official language;</li> <li><strong>When to Visit: </strong>The best time to visit Greece is during the spring (April to June) and autumn (September to October) when the weather is mild and the crowds are smaller;</li> <li><strong>Hints: </strong> Explore the ancient ruins of Athens, relax on the beaches of Santorini, and sample traditional Greek dishes like moussaka and souvlaki</li></ul>",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Greece.svg/1280px-Flag_of_Greece.svg.png"
        },

        "Ireland": {
            "description":"<h1>Ireland</h1> <ul> <li><strong>History: </strong> Ireland has a long and complex history, with influences from Celtic, Viking, and Norman cultures. It was part of the British Empire until gaining independence in 1922;</li> <li><strong>Economy: </strong> Ireland has a modern and open economy, with a strong focus on technology, finance, and agriculture. It is known as the <strong>Celtic</strong> Tiger for its rapid economic growth in the late 20th century;</li> <li><strong>Culture & Traditions: </strong> Ireland is known for its friendly people, lively pubs, and stunning landscapes. It has a rich literary and musical heritage, with famous writers like James Joyce and musicians like U2; </li> <li><strong>Languages: </strong> Irish and English are the official languages;</li> <li><strong>When to Visit: </strong>The best time to visit Ireland is during the summer months (June to August) when the weather is mild and the days are long;</li> <li><strong>Hints: </strong>Explore the vibrant city of Dublin, drive along the scenic Ring of Kerry, and visit ancient sites like the Rock of Cashel and Newgrange.</li></ul>",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Flag_of_Ireland.svg/300px-Flag_of_Ireland.svg.png"
        },
        "Italy": {
            "description":"<h1>Italia</h1> <ul> <li><strong>History: </strong> Italy has a rich and diverse history, from the Roman Empire to the Renaissance and beyond. It has been a center of art, culture, and commerce for centuries;</li> <li><strong>Economy: </strong>Italy has a mixed economy with a strong focus on manufacturing, tourism, and agriculture. It is known for its luxury goods, fashion industry, and automotive sector;</li> <li><strong>Culture & Traditions: </strong>     Italy is known for its art, architecture, food, and wine. It has a rich cultural heritage, with iconic landmarks like the Colosseum, Michelangelo's David, and the Vatican City; </li> <li><strong>Languages: </strong> Italian is the official language;</li> <li><strong>When to Visit: </strong> The best time to visit Italy depends on your interests. Spring (April to June) and autumn (September to October) are generally considered the best times to avoid crowds and enjoy mild weather;</li> <li><strong>Hints: </strong> Explore the historic city of Rome, indulge in pasta and gelato in Florence, and cruise along the Amalfi Coast.</li></ul>",
            "image": "https://upload.wikimedia.org/wikipedia/en/thumb/0/03/Flag_of_Italy.svg/300px-Flag_of_Italy.svg.png"
        },
        "Latvia": {
            "description":"<h1>Latvia</h1> <ul> <li><strong>History: </strong> Latvia has a long history of being ruled by various powers, including the Germans, Swedes, and Russians. It gained independence in 1918 but was occupied by the Soviet Union during World War II;</li> <li><strong>Economy:</strong>Latvia has a modern market economy with a strong focus on manufacturing, services, and tourism. It has experienced rapid economic growth since joining the European Union in 2004;</li> <li><strong>Culture & Traditions: </strong>   Latvia has a rich cultural heritage, with influences from its Baltic, German, and Russian neighbors. It is known for its traditional music, dance, and handicrafts; </li> <li><strong>Languages: </strong> Latvian is the official language;</li> <li><strong>When to Visit:</strong> The best time to visit Latvia is during the summer months (June to August) when the weather is warm and the days are long;</li> <li><strong>Hints: </strong> Explore the historic center of Riga, visit the seaside resort town of Jurmala, and experience traditional Latvian sauna rituals.</li></ul>",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Flag_of_Latvia.svg/300px-Flag_of_Latvia.svg.png"
        },

        "Lithuania": {
            "description":"<h1>Lithuania</h1> <ul> <li><strong>History: </strong>  Lithuania has a long and complex history, from the medieval Grand Duchy of Lithuania to its occupation by the Soviet Union during World War II. It regained independence in 1990;</li> <li><strong>Economy: </strong> Lithuania has a modern market economy with a strong focus on manufacturing, services, and technology. It has one of the fastest-growing economies in the European Union;</li> <li><strong>Culture & Traditions: </strong> Lithuania has a rich cultural heritage, with influences from its Baltic, Polish, and Russian neighbors. It is known for its traditional music, dance, and festivals; </li> <li><strong>Languages: </strong>  Lithuanian is the official language;</li> <li><strong>When to Visit: </strong> the best time to visit Lithuania is during the summer months (June to August) when the weather is warm and the days are long;</li> <li><strong>Hints: </strong>Explore the historic Old Town of Vilnius, visit the medieval castle of Trakai, and explore the scenic Curonian Spit.</li></ul>",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Flag_of_Lithuania.svg/300px-Flag_of_Lithuania.svg.png"
        },
        "Luxembourg": {
            "description":"<h1>Luxembourg</h1> <ul> <li><strong>History: </strong>  Luxembourg has a long history of being ruled by various powers, including the Burgundians, Spanish, French, and Germans. It became an independent grand duchy in 1815;</li> <li><strong>Economy: </strong> Luxembourg has a highly developed and diversified economy, with a strong focus on finance, services, and technology. It is one of the wealthiest countries in the world;</li> <li><strong>Culture & Traditions: </strong>  Luxembourg has a rich cultural heritage, with influences from its neighbors like France, Germany, and Belgium. It is known for its historic castles, picturesque villages, and scenic landscapes; </li> <li><strong>Languages: </strong>   Luxembourgish, French, and German are the official languages;</li> <li><strong>When to Visit:</strong> The best time to visit Luxembourg is during the summer months (June to August) when the weather is mild and the countryside is green;</li> <li><strong>Hints: </strong> Explore the capital city of Luxembourg, visit the medieval castle of Vianden, and hike in the beautiful Müllerthal region.</li></ul>",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Flag_of_Luxembourg.svg/300px-Flag_of_Luxembourg.svg.png"
        },
        "Malta": {
            "description":"<h1>Malta</h1> <ul> <li><strong>History: </strong> Malta has a long and diverse history, with influences from ancient civilizations like the Phoenicians, Romans, Arabs, and Knights of St. John. It gained independence from British rule in 1964;</li> <li><strong>Economy: </strong> Malta has a small but highly developed economy with a strong focus on tourism, finance, and manufacturing. It has experienced rapid economic growth in recent years;</li> <li><strong>Culture & Traditions:</strong>   Malta has a rich cultural heritage, with a unique blend of Mediterranean, Arab, and European influences. It is known for its historic sites, beautiful beaches, and vibrant festivals; </li> <li><strong>Languages: </strong> Maltese and English are the official languages;</li> <li><strong>When to Visit: </strong> The best time to visit Malta is during the spring (April to June) and autumn (September to November) when the weather is mild and the crowds are smaller;</li> <li><strong>Hints: </strong> Explore the historic capital city of Valletta, visit the ancient temples of Ħaġar Qim and Mnajdra, and relax on the beaches of Gozo.</li></ul>",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flag_of_Malta.svg/300px-Flag_of_Malta.svg.png"
        },
        "Netherlands": {
            "description":"<h1>Netherlands</h1> <ul> <li><strong>History: </strong>   The Netherlands has a long history of being ruled by various powers, including the Romans, Franks, Spanish, and French. It gained independence from Spanish rule in the 16th century;</li> <li><strong>Economy: </strong> The Netherlands has a highly developed and diversified economy, with a strong focus on international trade, finance, and agriculture. It is known for its innovative and entrepreneurial spirit;</li> <li><strong>Culture & Traditions: </strong>   The Netherlands is known for its tulip fields, windmills, and canals. It has a rich cultural heritage, with famous artists like Rembrandt and Van Gogh, as well as iconic landmarks like the Anne Frank House and Rijksmuseum;</li> <li><strong>Languages: </strong> Dutch is the official language;</li> <li><strong>When to Visit:</strong> The best time to visit the Netherlands is during the spring (April to May) when the tulips are in bloom, or during the summer months (June to August) for outdoor activities; </li> <li><strong>Hints: </strong>Explore the historic canal rings of Amsterdam, visit the picturesque villages of Giethoorn and Kinderdijk, and cycle through the scenic countryside.</li></ul>",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_the_Netherlands.svg/300px-Flag_of_the_Netherlands.svg.png"
        },

        "Portugal": {
            "description":"<h1>Portugal</h1> <ul> <li><strong>History: </strong>   Portugal has a long and storied history, from its days as a Roman province to its era as a global maritime power during the Age of Discovery. It was one of the earliest European nations to explore and colonize overseas territories;</li> <li><strong>Economy: </strong> Portugal has a mixed economy with a strong focus on tourism, manufacturing, and services. It has experienced significant economic growth and modernization since joining the European Union in 1986;</li> <li><strong>Culture & Traditions: </strong>  Portugal is known for its rich cultural heritage, with influences from its diverse history and global empire. It is famous for its Fado music, azulejos (painted tiles), and delicious cuisine, including pastéis de nata (custard tarts) and bacalhau (salted cod);</li> <li><strong>Languages:</strong> Portuguese is the official language;</li> <li><strong>When to Visit: </strong> The best time to visit Portugal depends on your interests. Spring (March to May) and autumn (September to October) are generally pleasant with mild weather and fewer crowds, while summer (June to August) is perfect for beachgoers and festival enthusiasts; </li> <li><strong>Hints: </strong>Explore the historic neighborhoods of Lisbon, wander through the enchanting streets of Porto, and relax on the beautiful beaches of the Algarve</li></ul>",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Portugal.svg/300px-Flag_of_Portugal.svg.png"
        },
        "Slovakia": {
            "description":"<h1>Slovakia</h1> <ul> <li><strong>History: </strong> Slovakia has a long and complex history, with influences from Celtic, Roman, Hungarian, and Austrian cultures. It was part of the Kingdom of Hungary until the formation of Czechoslovakia in 1918;</li> <li><strong>Economy: </strong> Slovakia has a modern market economy with a strong focus on manufacturing, automotive, and services. It has experienced significant economic growth since joining the European Union in 2004;</li> <li><strong>Culture & Traditions: </strong> Slovakia has a rich cultural heritage, with influences from its Slavic, Hungarian, and Austrian neighbors. It is known for its traditional folk music, dance, and handicrafts;</li> <li><strong>Languages: </strong> Slovak is the official language;</li> <li><strong>When to Visit: </strong> The best time to visit Slovakia is during the summer months (June to August) when the weather is warm and the countryside is green; </li> <li><strong>Hints: </strong>Explore the historic city of Bratislava, hike in the Tatra Mountains, and visit the medieval castles of Spišský Hrad and Orava Castle</li></ul>",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Flag_of_Slovakia.svg/300px-Flag_of_Slovakia.svg.png"
        },

        "Slovenia": {
            "description":"<h1>Slovakia</h1> <ul> <li><strong>History: </strong>  Slovenia has a long and diverse history, with influences from Celtic, Roman, Slavic, and Austrian cultures. It was part of various empires, including the Roman Empire and the Habsburg monarchy, before becoming part of Yugoslavia in the 20th century. It gained independence in 1991;</li> <li><strong>Economy: </strong>  Slovenia has a modern and open economy with a strong focus on manufacturing, services, and tourism. It has experienced rapid economic growth and development since gaining independence;</li> <li><strong>Culture & Traditions: </strong>  Slovenia has a rich cultural heritage, with influences from its diverse history and geography. It is known for its traditional music, dance, and cuisine, as well as its stunning natural landscapes, including the Julian Alps and Lake Bled;</li> <li><strong>Languages: </strong> Slovene is the official language;</li> <li><strong>When to Visit:</strong> The best time to visit Slovenia depends on your interests. Spring (April to June) and autumn (September to October) are generally pleasant with mild weather and fewer crowds, while summer (July to August) is perfect for outdoor activities; </li> <li><strong>Hints: </strong>Explore the historic city of Bratislava, hike in the Tatra Mountains, and visit the medieval castles of Spišský Hrad and Orava Castle</li></ul>",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Flag_of_Slovenia.svg/300px-Flag_of_Slovenia.svg.png"
        },

        "Spain": {
            "description":"<h1>Spain</h1> <ul> <li><strong>History:</strong>  Spain has a long and storied history, from its days as a Roman province to its era as a global maritime power during the Age of Discovery. It was ruled by various kingdoms and empires, including the Moors, before becoming a unified kingdom in the 15th century;</li> <li><strong>Economy: </strong>  Spain has a mixed economy with a strong focus on tourism, manufacturing, and services. It is one of the world's top tourist destinations, known for its beaches, historic cities, and vibrant culture;</li> <li><strong>Culture & Traditions: </strong> Spain is known for its rich cultural heritage, with influences from its diverse history and regions. It is famous for its flamenco music and dance, bullfighting, and traditional festivals like Semana Santa (Holy Week) and La Tomatina;</li> <li><strong>Languages: </strong>  Spanish is the official language;</li> <li><strong>When to Visit:</strong> he best time to visit Spain depends on your interests. Spring (March to May) and autumn (September to November) are generally pleasant with mild weather and fewer crowds, while summer (June to August) is perfect for beachgoers and festival enthusiasts; </li> <li><strong>Hints: </strong>Explore the historic neighborhoods of Barcelona, visit the iconic Alhambra in Granada, and relax on the beaches of the Costa del Sol</li></ul>",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Bandera_de_Espa%C3%B1a.svg/300px-Bandera_de_Espa%C3%B1a.svg.png"
        },
        
        

         
         
        // Add data for other countries similarly...
    };

    $("#tags").autocomplete({
        source: Object.keys(countryData),
        select: function (event, ui) {
            var selectedCountry = ui.item.value;
            var countryInfo = countryData[selectedCountry];
            $("#country").html('<img src="' + countryInfo.image + '" alt="' + selectedCountry + '">' + countryInfo.description);
        }
    });
});


$(document).ready(function () {
    $("#list li").draggable({
        revert: 'invalid', // Quando non rilasciato, l'elemento tornerà alla sua posizione iniziale
        helper: 'clone', // Crea un clone dell'elemento trascinabile mentre viene trascinato
        stop: function(event, ui) {
            $("#tags").val(''); // Svuota il campo di input #tags
        }
    });

    $("#tags").droppable({
        drop: function(event, ui) {
            var droppedText = ui.draggable.text().trim();
            displayCountryInfo(droppedText);
            $(this).autocomplete("search", droppedText); // Avvia la ricerca dell'autocompletamento
        }
    });

    function displayCountryInfo(country) {
        
        $("#country").html("<p>Informazioni su " + country + " qui.</p>");
    }
});